name: blockbuster # app name'
version: '0.2' # git tag version'
summary: Search for your favourite movies # 79 char long summary
description: |
  Update your movie database:-
    $ blockbuster -r
  Search by category
    $ blockbuster -g action
  Search by name and print as JSON
    $ blockbuster -j "The movie"
icon: icon.png

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  blockbuster-part:
    # See 'snapcraft plugins'
    plugin: python
    source: https://github.com/NunuM/movies_command.git
    source-tag: v0.2
  config-part:
    plugin: dump
    source: https://github.com/NunuM/movies_command.git
    source-tag: v0.2
    organize:
      'config.cfg' : $SNAP_USER_COMMON/

apps:
  blockbuster:
    command: blockbuster
    plugs: 
      - home
      - network
